### PR TITLE
Add swift support

### PR DESCRIPTION
**Pull request by nathankot**
Not able to import this module in a swift project (using cocoapods)
because it hasn't linked to a modulemap, this fixes it :)

### CODE REVIEW

**Comment by cwRichardKim** [comment]
Thanks! Asking for the sake of the readme, is there any further setup required to make this work? I found this online: "Note that consumers of any frameworks you build using this technique are also going to have to add the module to their Swift search paths."

**Comment by nathankot** [comment]
Hey @cwRichardKim where did you find that quote? There's no extra step that I know of, except perhaps `use_frameworks!` but that is generally for when you want to include swift dependencies

**Comment by schickling** [comment]
Please merge this!

**Comment by schickling** [comment]
That was fast! :+1:

**Comment by cwRichardKim** [comment]
hahaha sorry i completely forgot about that

**Pull request merged**
